analyzer:
  errors:
    use_build_context_synchronously: ignore
    unused_element: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true